DPCPP_CXX = dpcpp
DPCPP_CXXFLAGS = -std=c++17 -g -o
DPCPP_LDFLAGS = -Werror
DPCPP_EXE_NAME = main
DPCPP_SOURCES = src/main.cpp

TEST_SOURCES = src/test_file.cpp
TEST_EXE_NAME = test_file


all:
	$(DPCPP_CXX) $(DPCPP_CXXFLAGS) $(DPCPP_EXE_NAME) $(DPCPP_SOURCES) $(DPCPP_LDFLAGS)


test:
	$(DPCPP_CXX) $(DPCPP_CXXFLAGS) $(TEST_EXE_NAME) $(TEST_SOURCES) $(DPCPP_LDFLAGS)
	./$(TEST_EXE_NAME)

run:
	./$(DPCPP_EXE_NAME)

clean: 
	rm -rf $(DPCPP_EXE_NAME)
	rm -rf $(TEST_EXE_NAME)


